version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongodb_dev
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongouser
      - MONGO_INITDB_ROOT_PASSWORD=secretpassword
      - MONGO_INITDB_DATABASE=coursekit
    ports:
      - "27017:27017"  
    volumes:
      - mongo_data:/data/db  

  mongo-express:
    image: mongo-express:latest
    container_name: mongo_express
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=mongouser
      - ME_CONFIG_MONGODB_ADMINPASSWORD=secretpassword
      - ME_CONFIG_MONGODB_SERVER=mongo
    ports:
      - "8081:8081"  

volumes:
  mongo_data: